[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
  "probe-rs",
  "run",
  "--chip",
  "RP2040",
  "--protocol",
  "swd",
  "--log-format",
  "[{f:dimmed}:{l:dimmed} {t}] {L:bold} {s}",
]
linker = "flip-link"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C", "no-vectorize-loops",
]


[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "info"

